### ISSUE TITLE
showhomepage.php

### ISSUE THREAD

**Issue by lijiarui** [zixia/ucapp#11]
add one para in the response list:

now the response data are as follows:
resp['b'][0]:
img: ["http://17salsa.com/home/attachment/201203/3/1_1330791912Vq3V.jpg.thumb.jpg"]
like: [1, 2]
p: ["1", "blues", "http://17salsa.com/center/data/avatar/000/00/00/01_real_avatar_middle.jpg"]
reply: [[1, "qqqq"], [2, "xxx"]]
ts: "1330791912"
txt: "HKSF 2012 17SALSA Speech"
type: "img"

add one para 'item_id'  let the response data as follows:
resp['b'][0]:
img: ["http://17salsa.com/home/attachment/201203/3/1_1330791912Vq3V.jpg.thumb.jpg"]
like: [1, 2]
p: ["1", "blues", "http://17salsa.com/center/data/avatar/000/00/00/01_real_avatar_middle.jpg"]
reply: [[1, "qqqq"], [2, "xxx"]]
ts: "1330791912"
txt: "HKSF 2012 17SALSA Speech"
type: "img"
item_id:'123456'

item_id 某个user_id发的第item_id个状态

**Comment by huan** [comment]
哦，看到item_id了
