### ISSUE TITLE
好友个人主页的内容都是自己朋友圈的内容

### ISSUE THREAD

**Issue by lijiarui** [zixia/ucapp#19]
http://localhost/#/personalContactHomepage/%7B%22id%22:59347,%22path%22:%22contact-detail%22%7D

所有好友的个人主页内容和自己朋友圈内容相同

已经传给后台user_id  后台吐出来的东西都是自己的好友状态更新

**Comment by huan** [comment]
it's because jiarui broke api protocol. fixed.
