### ISSUE TITLE
sendlike api

### ISSUE THREAD

**Issue by lijiarui** [zixia/ucapp#6]
function:friendcircle send like

error:already pushed but can't find in http://17salsa.com/ucapp/ucapi/receivelike.php
404 error

status:api written

tobedo:zixia complete sendlike api----'receivelike.php'

**Comment by huan** [comment]
questions:
1. what is $user? need sample data and comment.
2. what should response data structure? need sample data and comment.

**Comment by lijiarui** [comment]
1、$user is userid.
2、if deal sendlike function successfully response resp['h']=0  no resp['b']

**Comment by huan** [comment]
user / userid / user_id ?

we need unify all param names in protocol.

**Comment by lijiarui** [comment]
this function need user_id

ps:user = {user_id, user_name,user_avatar}  how about this name?

**Comment by huan** [comment]
what is the difference between user_id & contact_id ?

**Comment by huan** [comment]
close the same issue #12  https://github.com/lijiarui/ucapp/issues/12
