### ISSUE TITLE
app下载网页的设计和制作

### ISSUE THREAD

**Issue by huan** [zixia/ucapp#60]
http://17salsa.com/ucapp

类似http://mocha.cn/ ，可以重用splash图片

**Comment by huan** [comment]
自由发挥吧，用那已经设计好的三张图，然后再参考这三方面内容： 
- 关于17SALSA： http://17salsa.com/wiki/doc-view-4.html
- 社区背静： http://17salsa.com/home/space-2-do-blog-id-418.html
- 团队照片： http://17salsa.com/home/attachment/201003/30/2_1269976247Miyb.jpg

**Comment by lijiarui** [comment]
http://17salsa.com/ucapp/ucapi/download/
