### ISSUE TITLE
sendremark api

### ISSUE THREAD

**Issue by lijiarui** [zixia/ucapp#7]
function:friendcircle send remark

error:already pushed 'receiveremark.php' but can't find in http://17salsa.com/ucapp/ucapi/receiveremark.php
404 error

status:api written

tobedo:zixia complete sendremark api----'receiveremark.php'

**Comment by huan** [comment]
it's there when I check:
-rwxr-xr-x 1 zixia zixia 834 Jun 14 15:18 receiveremark.php

**Comment by huan** [comment]
the same as #13
